apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-mysql
  template:
    metadata:
      labels:
        app: java-mysql
    spec:
      imagePullSecrets:
        - name: dockerhub-secret  # <--- ADD this for private docker image
      containers:
        - name: java-container
          image: skillstute/java-mysql:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: DB_HOST_1
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_HOST

            - name: DB_PORT_1
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_PORT

            - name: DB_NAME_1
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_NAME

            - name: DB_USER_1
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USER

            - name: DB_PASSWORD_1
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
