apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-mysql
  template:
    metadata:
      labels:
        app: java-mysql
    spec:
      imagePullSecrets:
        - name: dockerhub-secret  # <--- ADD THIS for private
      containers:
        - name: java-container
          image: skillstute/java-mysql:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
