apiVersion: v1
kind: Service
metadata:
  name: java-mysql-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: java-mysql
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 30200
